//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyTelegramBot.Services.ResourcesAndConstants {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyTelegramBot.Services.ResourcesAndConstants.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} exchange rates are:.
        /// </summary>
        public static string BaseCurrencyLitForma {
            get {
                return ResourceManager.GetString("BaseCurrencyLitForma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, select the currency:.
        /// </summary>
        public static string CurrencySelect {
            get {
                return ResourceManager.GetString("CurrencySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong.I will fix it as soon as possible. Come back later..
        /// </summary>
        public static string ErrorBaseMessage {
            get {
                return ResourceManager.GetString("ErrorBaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I can not find it. Try again or come back later..
        /// </summary>
        public static string ErrorCanNotFind {
            get {
                return ResourceManager.GetString("ErrorCanNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no available rates at the moment. Try another date or try again later..
        /// </summary>
        public static string ErrorRatesCount {
            get {
                return ResourceManager.GetString("ErrorRatesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong BaseCurrency format..
        /// </summary>
        public static string ErrorWrongBaseCurrencyFormat {
            get {
                return ResourceManager.GetString("ErrorWrongBaseCurrencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong date format! Please, write date in &apos;dd.mm.yyyy&apos;(01.01.2022) or &apos;dd/mm/yyyy&apos;(01/01/2022) format..
        /// </summary>
        public static string ErrorWrongDateFormat {
            get {
                return ResourceManager.GetString("ErrorWrongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I can not see the future! Try again..
        /// </summary>
        public static string ErrorWrongDateFuture {
            get {
                return ResourceManager.GetString("ErrorWrongDateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It was too long time ago. I only remember the exchange rate for the last 4 years. Try again..
        /// </summary>
        public static string ErrorWrongDateToLongAgo {
            get {
                return ResourceManager.GetString("ErrorWrongDateToLongAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - {1}/{2}.
        /// </summary>
        public static string ExchangeRateForma {
            get {
                return ResourceManager.GetString("ExchangeRateForma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}/{1}.
        /// </summary>
        public static string MinorCurrencyForma {
            get {
                return ResourceManager.GetString("MinorCurrencyForma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today&apos;s exchange rate.
        /// </summary>
        public static string ReplyMarkupToday {
            get {
                return ResourceManager.GetString("ReplyMarkupToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EUR today.
        /// </summary>
        public static string ReplyMarkupTodayEUR {
            get {
                return ResourceManager.GetString("ReplyMarkupTodayEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USD today.
        /// </summary>
        public static string ReplyMarkupTodayUSD {
            get {
                return ResourceManager.GetString("ReplyMarkupTodayUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} to {1} exchange rate on the this date({2}) was: .
        /// </summary>
        public static string SelectedRatesForma {
            get {
                return ResourceManager.GetString("SelectedRatesForma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today`s {0} to {1} exchange rate is: .
        /// </summary>
        public static string TodaySelectedRatesForma {
            get {
                return ResourceManager.GetString("TodaySelectedRatesForma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Todey&apos;s {0} exchange rates are:.
        /// </summary>
        public static string TodeyBaseCurrencyLitForma {
            get {
                return ResourceManager.GetString("TodeyBaseCurrencyLitForma", resourceCulture);
            }
        }
    }
}
